name: Build and Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build release binary
        shell: bash
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: parms-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/parms
