name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: parms
          path: ./target/release/parms
